In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.getcwd()

'C:\\Users\\Tatiana\\Downloads'

In [3]:
data=pd.read_csv('data.csv')

In [4]:
np.__version__

'1.19.2'

In [5]:
data.shape

(11914, 16)

In [6]:
data.groupby(['Make']).count().sort_values('Model', ascending=False).head()

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                     
Chevrolet    1123  1123              1123       1117              1121   
Ford          881   881               881        868               881   
Volkswagen    809   809               809        809               805   
Toyota        746   746               746        744               745   
Dodge         626   626               626        626               626   

            Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                            
Chevrolet                1123           1123             1123   
Ford                      881            881              881   
Volkswagen                809            809              809   
Toyota                    746            746              746   
Dodge                     626            626              626   

            Market Category  Vehicle Size  Vehicle Style  highway MPG  \
Make                                                                    
Chevrolet               622          1123           1123         1123   
Ford                    499           881            881          881   
Volkswagen              585           809            809          809   
Toyota                  303           746            746          746   
Dodge                   320           626            626          626   

            city mpg  Popularity  MSRP  
Make                                    
Chevrolet       1123        1123  1123  
Ford             881         881   881  
Volkswagen       809         809   809  
Toyota           746         746   746  
Dodge            626         626   626

In [7]:
data.loc[data.Make=='Audi',['Model']].drop_duplicates().count()

Model    34
dtype: int64

In [8]:
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [9]:
data["Engine Cylinders"].median()

6.0

In [10]:
data["Engine Cylinders"].mode()

0    4.0
dtype: float64

In [11]:
data.loc[:,"Engine Cylinders"] = data.loc[:,"Engine Cylinders"].fillna(4)

In [12]:
data["Engine Cylinders"].median()

6.0

In [13]:
X=data.loc[data.Make == 'Lotus',["Engine HP", "Engine Cylinders"]].drop_duplicates().values

In [14]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [15]:
XTX=X.T.dot(X)

In [16]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [17]:
np.linalg.inv(XTX)

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
y=[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [19]:
w=np.linalg.inv(XTX).dot(X.T)
w.dot(y)

array([  4.59494481, -63.56432501])